try {
    Set-Location $PSScriptRoot
    Remove-Item ".git\index.lock" -Force -ErrorAction SilentlyContinue
    Remove-Item ".git\HEAD.lock" -Force -ErrorAction SilentlyContinue
    git add src/app/api/trips/`[id`]/route.ts src/components/RecordingProvider.tsx src/app/catch/new/page.tsx src/app/landing/page.tsx src/components/map/MapScreen.tsx src/components/TripDetailSheet.tsx src/app/api/catch/route.ts src/components/LiveScanCamera.tsx src/components/FeedCard.tsx src/components/ui.tsx src/app/post/`[id`]/page.tsx src/app/post/`[id`]/PostDetailClient.tsx src/app/about/page.tsx src/app/api/bookings/route.ts src/app/api/points/recommend/route.ts src/app/api/posts/`[id`]/bookmark/route.ts src/app/api/posts/`[id`]/comments/route.ts src/app/api/posts/`[id`]/like/route.ts src/app/api/tournaments/route.ts src/app/api/users/`[id`]/follow/route.ts src/app/feed/page.tsx src/components/market/MarketChatRoom.tsx src/lib/queries.ts src/lib/rateLimit.ts src/app/api/measure/scan/route.ts src/components/IpnakBallPurchase.tsx src/app/log/`[id`]/page.tsx src/app/market/`[id`]/page.tsx src/app/landing/page.tsx src/app/groups/`[id`]/page.tsx src/components/GroupPointsMap.tsx src/app/api/me/log-posts/route.ts src/app/api/geocode/route.ts src/app/globals.css src/lib/groupPosts.ts src/app/api/groups/`[id`]/posts/`[postId`]/comments/route.ts src/components/AppShell.tsx src/components/market/MarketList.tsx src/app/admin/market/page.tsx src/components/admin/AdminShell.tsx src/app/api/admin/action/route.ts src/app/api/admin/seed-market/route.ts src/components/admin/MarketSeedButton.tsx src/app/me/page.tsx src/app/market/favorites/page.tsx src/app/market/purchases/page.tsx src/components/market/MarketChatRoom.tsx src/app/market/chats/`[id`]/page.tsx src/app/market/chats/page.tsx src/components/market/MarketDetailActions.tsx
    git commit -m "fix: fish catch count showing 0 in card and detail sheet`nfeat: GPS 경로 정확도 개선 (정확도 30m 필터, 최소 3m 이동 필터, maximumAge=0)`nfix: 가로 모드 직접 측정 시 이미지 누워서 보이는 문제 수정`nfeat: 피드 캐러셀 슬라이드 자연스러운 전환 애니메이션 및 손가락 추적 드래그 구현`nfix: 피드 캐러셀 가로 드래그 중 세로 스크롤 간섭 제거 (non-passive touchmove)`nfix: 좋아요/저장 후 다른 페이지 갔다 돌아와도 상태 유지 (router.refresh로 라우터 캐시 무효화)`nfix: 댓글 입력창 터치 시 키보드가 Sheet를 가리는 문제 수정 (visualViewport 기반 max-height 동적 조정)`nfeat: 피드 상세페이지 아래로 스와이프하면 이전 페이지로 돌아가기`nfix: 페이블 모델 전체 검수 - race condition, 메모리 누수, API 에러 핸들링, 쿼리 최적화`nfix: iOS 입력창 자동 확대 방지 (font-size 16px 전역 !important 적용)`nfeat: 조행기·중고거래 상세페이지 아래로 스와이프하면 이전 페이지로 돌아가기`nfeat: AI 스캔·추천 API 요청 횟수 제한 (분당 5회/3회)`nfix: 랜딩페이지·about페이지 메인 카피 3줄→2줄 (낚시인의 모든 / 순간을 기록하다)`nfeat: 소모임 포인트공유정보 탭 - 탭·버튼 텍스트 변경, 내기록추가, 주소검색, iOS줌방지, X닫기 단계별 뒤로가기`nfeat: 낚시단 커뮤니티 댓글 대댓글 기능 추가 (답글 달기, 답글 입력창, 들여쓰기 표시)`nfeat: 모바일 하단 메뉴 홈→커뮤니티 변경 (초기 진입은 홈, PC메뉴는 기존 유지)`nfeat: 중고피싱 당근마켓 스타일 고도화 - 리스트형 UI, 상세 판매자/거래정보, 판매자 다른상품`nfeat: 관리자 중고피싱 관리 페이지 추가 - 목록/상태변경/삭제 (admin/market)`nfeat: admin action API에 MARKET_STATUS, MARKET_DELETE 액션 추가`nfeat: 중고피싱 고도화 - 마이페이지 중고피싱 관리 섹션 추가 (판매/구매/관심/채팅)`nfeat: 관심목록 페이지 추가 (/market/favorites)`nfeat: 구매내역 페이지 추가 (/market/purchases)`nfeat: 중고피싱 상세 통계(관심/채팅/조회) 크게 개선 (grid 3열, 아이콘+숫자+라벨)`nfeat: 채팅 고도화 - 상품별 채팅, 날짜 구분선, 시스템 메시지, 말풍선 연속 묶음`nfeat: 판매자 채팅방 내 예약하기/예약취소/거래완료 버튼 추가`nfeat: 구매자 채팅방 내 예약 요청하기 버튼 추가`nfeat: MarketDetailActions 예약중 안내 배너 + 상태별 버튼 색상 개선`nfeat: 채팅 목록 UI 개선 - 상품 썸네일 크게, 상태 뱃지 오버레이, 시스템메시지 이탤릭"
    git remote set-url origin https://github.com/nan29077/ipnak.git
    git push origin main --force
    Write-Host "Done!" -ForegroundColor Green
} catch {
    Write-Host "Error: $_" -ForegroundColor Red
} finally {
    Read-Host "Press Enter to close"
}
