import Link from "next/link";
import { prisma } from "@/lib/prisma";
import { getSetting } from "@/lib/settings";
import { AdminTitle, StatusBadge, Table } from "@/components/admin/ui";
import { BallPriceForm, BallStatusActions } from "@/components/admin/IpnakBallAdminActions";
import { cn, kstFormat } from "@/lib/utils";
export const dynamic = "force-dynamic";

const tabs = [{ key: "requests", label: "구매 요청" }, { key: "orders", label: "주문 관리" }, { key: "payments", label: "결제 관리" }, { key: "shipping", label: "배송 관리" }, { key: "price", label: "가격 설정" }];
export default async function BallAdmin({ searchParams }: { searchParams: { tab?: string } }) {
  const tab = tabs.some(t => t.key === searchParams.tab) ? searchParams.tab! : "requests";
  const price = Number(await getSetting("ipnak_ball_price"));
  const where = tab === "requests" ? { status: { in: ["REQUESTED", "PAID"] } } : tab === "payments" ? { paymentStatus: { in: ["READY", "PAID", "CANCELLED", "REFUNDED"] } } : tab === "shipping" ? { status: { in: ["PREPARING", "SHIPPED", "DELIVERED"] } } : {};
  const orders = tab === "price" ? [] : await prisma.ballOrder.findMany({ where, include: { user: { select: { nickname: true, email: true } } }, orderBy: { createdAt: "desc" }, take: 200 });
  return <div><AdminTitle title="입낚볼 관리" desc="구매 요청부터 결제 승인, 주문 처리, 배송 완료까지 통합 관리합니다."/><div className="mb-5 flex flex-wrap gap-1.5 border-b border-navy-100">{tabs.map(t => <Link key={t.key} href={`/admin/ipnak-ball?tab=${t.key}`} className={cn("border-b-2 px-3 py-2.5 text-[13px] font-semibold", tab === t.key ? "border-orange-500 text-orange-500" : "border-transparent text-navy-400")}>{t.label}</Link>)}</div>{tab === "price" ? <BallPriceForm initial={price}/> : <><div className="mb-3 grid grid-cols-2 gap-3 md:grid-cols-4"><Summary label="조회 주문" value={`${orders.length}건`}/><Summary label="결제 금액" value={`${orders.filter(o => o.paymentStatus === "PAID").reduce((s,o) => s + o.totalPrice, 0).toLocaleString()}원`}/><Summary label="배송 준비" value={`${orders.filter(o => o.status === "PREPARING").length}건`}/><Summary label="배송 중" value={`${orders.filter(o => o.status === "SHIPPED").length}건`}/></div><Table head={["주문번호·일시", "구매자", "배송지", "상품금액", "결제", "주문/배송", "관리"]}>{orders.length === 0 && <tr><td colSpan={7} className="px-4 py-12 text-center text-navy-400">해당 내역이 없습니다.</td></tr>}{orders.map(o => <tr key={o.id}><td className="whitespace-nowrap px-4 py-3"><p className="font-semibold text-navy-800">{o.orderNo}</p><p className="text-xs text-navy-400">{kstFormat(o.createdAt, "yyyy.MM.dd HH:mm")}</p></td><td className="px-4 py-3"><p>{o.buyerName} · {o.buyerPhone}</p><p className="text-xs text-navy-400">{o.user.nickname} ({o.user.email})</p></td><td className="max-w-[260px] px-4 py-3 text-xs"><p>{o.recipientName} · {o.recipientPhone}</p><p className="mt-0.5 text-navy-400">({o.postalCode}) {o.address} {o.addressDetail}</p>{o.trackingNumber && <p className="mt-1 text-aqua-400">{o.carrier} {o.trackingNumber}</p>}</td><td className="whitespace-nowrap px-4 py-3 font-bold">{o.totalPrice.toLocaleString()}원<p className="text-xs font-normal text-navy-400">{o.quantity}개 × {o.unitPrice.toLocaleString()}</p></td><td className="px-4 py-3"><StatusBadge status={o.paymentStatus}/><p className="mt-1 text-xs text-navy-400">{o.paymentMethod || "-"}</p></td><td className="px-4 py-3"><StatusBadge status={o.status}/></td><td className="px-4 py-3"><BallStatusActions id={o.id} status={o.status}/></td></tr>)}</Table></>}</div>;
}
function Summary({ label, value }: { label: string; value: string }) { return <div className="card p-4"><p className="text-xs text-navy-400">{label}</p><p className="mt-1 text-xl font-extrabold text-navy-800">{value}</p></div>; }
